package com.example.CarDealership.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * Data Transfer Object for Car.
 * 
 * Used to transfer car data via the API. Provides validation for vehicle attributes.
 * Note: Car ID is never included in requests (generated by the server).
 */
@Schema(description = "Car Data Transfer Object")
public class CarDTO {

    @Schema(description = "Unique identifier (server-generated)", example = "1", accessMode = Schema.AccessMode.READ_ONLY)
    private Long id;

    @Schema(description = "Car brand/manufacturer", example = "Toyota")
    @NotBlank(message = "Brand is required")
    @Size(min = 2, max = 50, message = "Brand must be between 2 and 50 characters")
    private String brand;

    @Schema(description = "Car model", example = "Corolla")
    @NotBlank(message = "Model is required")
    @Size(min = 2, max = 50, message = "Model must be between 2 and 50 characters")
    private String model;

    @Schema(description = "Manufacturing year", example = "2023")
    @Min(value = 1980, message = "Year must be at least 1980")
    private int year;

    @Schema(description = "Car price in USD", example = "25000.00")
    @DecimalMin(value = "0.01", message = "Price must be greater than 0")
    private double price;

    // Constructors
    public CarDTO() {}

    public CarDTO(Long id, String brand, String model, int year, double price) {
        this.id = id;
        this.brand = brand;
        this.model = model;
        this.year = year;
        this.price = price;
    }

    // Getters & Setters
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getBrand() { return brand; }
    public void setBrand(String brand) { this.brand = brand; }

    public String getModel() { return model; }
    public void setModel(String model) { this.model = model; }

    public int getYear() { return year; }
    public void setYear(int year) { this.year = year; }

    public double getPrice() { return price; }
    public void setPrice(double price) { this.price = price; }
}
