package com.example.CarDealership.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;

/**
 * Data Transfer Object for Employee.
 * 
 * Used to transfer employee data via the API. Hides internal database structure
 * and provides comprehensive validation at the API boundary.
 * Note: Employee ID is never included in requests (generated by the server).
 */
@Schema(description = "Employee Data Transfer Object")
public class EmployeeDTO {

    @Schema(description = "Unique identifier (server-generated)", example = "1", accessMode = Schema.AccessMode.READ_ONLY)
    private Long id;

    @Schema(description = "Employee first name", example = "Jane")
    @NotBlank(message = "First name is required")
    @Size(min = 2, max = 50, message = "First name must be between 2 and 50 characters")
    private String firstName;

    @Schema(description = "Employee last name", example = "Smith")
    @NotBlank(message = "Last name is required")
    @Size(min = 2, max = 50, message = "Last name must be between 2 and 50 characters")
    private String lastName;

    @Schema(description = "Employee email address (must be unique)", example = "jane.smith@cardealership.com")
    @NotBlank(message = "Email is required")
    @Email(message = "Email should be valid")
    private String email;

    @Schema(description = "Employee phone number", example = "+250788123456")
    @NotBlank(message = "Phone number is required")
    @Pattern(regexp = "^\\+?[0-9]{10,15}$", message = "Phone number must be valid (10-15 digits)")
    private String phoneNumber;

    @Schema(description = "Employee salary in USD", example = "1500.00")
    @DecimalMin(value = "0.01", message = "Salary must be greater than 0")
    private double salary;

    @Schema(description = "Location ID (assigned location)", example = "550e8400-e29b-41d4-a716-446655440005")
    @NotBlank(message = "Location ID is required")
    private String locationId;

    @Schema(description = "Location name (read-only)", example = "Kigali")
    private String locationName;

    // Constructors
    public EmployeeDTO() {}

    public EmployeeDTO(Long id, String firstName, String lastName, String email, String phoneNumber, double salary, String locationId) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.salary = salary;
        this.locationId = locationId;
    }

    // Getters & Setters
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getFirstName() { return firstName; }
    public void setFirstName(String firstName) { this.firstName = firstName; }

    public String getLastName() { return lastName; }
    public void setLastName(String lastName) { this.lastName = lastName; }

    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }

    public String getPhoneNumber() { return phoneNumber; }
    public void setPhoneNumber(String phoneNumber) { this.phoneNumber = phoneNumber; }

    public double getSalary() { return salary; }
    public void setSalary(double salary) { this.salary = salary; }

    public String getLocationId() { return locationId; }
    public void setLocationId(String locationId) { this.locationId = locationId; }

    public String getLocationName() { return locationName; }
    public void setLocationName(String locationName) { this.locationName = locationName; }
}
