package com.example.CarDealership.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.FutureOrPresent;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import java.time.LocalDate;
import java.util.List;

/**
 * Data Transfer Object for Sale.
 * 
 * Used to transfer sale data via the API. Includes customer ID, employee ID,
 * and a list of car IDs (for many-to-many relationship).
 * Note: Sale ID is never included in requests (generated by the server).
 */
@Schema(description = "Sale Data Transfer Object")
public class SaleDTO {

    @Schema(description = "Unique identifier (server-generated)", example = "1", accessMode = Schema.AccessMode.READ_ONLY)
    private Long id;

    @Schema(description = "Sale date", example = "2024-06-07")
    @NotNull(message = "Sale date is required")
    @FutureOrPresent(message = "Sale date cannot be in the past")
    private LocalDate saleDate;

    @Schema(description = "Final sale price in USD", example = "25000.00")
    @NotNull(message = "Final price is required")
    @DecimalMin(value = "0.01", message = "Price must be greater than 0")
    private double finalPrice;

    @Schema(description = "Payment method", example = "CASH", allowableValues = {"CASH", "CARD"})
    @NotNull(message = "Payment method is required")
    private String paymentMethod;

    @Schema(description = "Customer ID", example = "550e8400-e29b-41d4-a716-446655440000")
    @NotNull(message = "Customer ID is required")
    private String customerId;

    @Schema(description = "Employee ID", example = "1")
    @NotNull(message = "Employee ID is required")
    private Long employeeId;

    @Schema(description = "List of car IDs being sold (many-to-many)", example = "[1, 2, 3]")
    @NotEmpty(message = "At least one car must be included in the sale")
    private List<Long> carIds;

    // Read-only response fields
    @Schema(description = "Customer name (read-only)", example = "John Doe")
    private String customerName;

    @Schema(description = "Employee name (read-only)", example = "Jane Smith")
    private String employeeName;

    @Schema(description = "List of cars in this sale (read-only)")
    private List<CarDTO> cars;

    // Constructors
    public SaleDTO() {}

    public SaleDTO(Long id, LocalDate saleDate, double finalPrice, String paymentMethod, 
                   String customerId, Long employeeId, List<Long> carIds) {
        this.id = id;
        this.saleDate = saleDate;
        this.finalPrice = finalPrice;
        this.paymentMethod = paymentMethod;
        this.customerId = customerId;
        this.employeeId = employeeId;
        this.carIds = carIds;
    }

    // Getters & Setters
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public LocalDate getSaleDate() { return saleDate; }
    public void setSaleDate(LocalDate saleDate) { this.saleDate = saleDate; }

    public double getFinalPrice() { return finalPrice; }
    public void setFinalPrice(double finalPrice) { this.finalPrice = finalPrice; }

    public String getPaymentMethod() { return paymentMethod; }
    public void setPaymentMethod(String paymentMethod) { this.paymentMethod = paymentMethod; }

    public String getCustomerId() { return customerId; }
    public void setCustomerId(String customerId) { this.customerId = customerId; }

    public Long getEmployeeId() { return employeeId; }
    public void setEmployeeId(Long employeeId) { this.employeeId = employeeId; }

    public List<Long> getCarIds() { return carIds; }
    public void setCarIds(List<Long> carIds) { this.carIds = carIds; }

    public String getCustomerName() { return customerName; }
    public void setCustomerName(String customerName) { this.customerName = customerName; }

    public String getEmployeeName() { return employeeName; }
    public void setEmployeeName(String employeeName) { this.employeeName = employeeName; }

    public List<CarDTO> getCars() { return cars; }
    public void setCars(List<CarDTO> cars) { this.cars = cars; }
}
